name: basic_triangle
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  ffi: ^2.1.2
  vulkan: ^1.3.226
  glew: ^1.2.0
  glfw3: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
